version: "3.9"

services:
  api:
    build: .
    container_name: backend-api
    ports:
      - "8000:8000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000

  worker:
    build: .
    container_name: backend-worker
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_healthy
    command: ["python", "run_worker.py"]
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongo_data: